-- AUTO-GENERATED BY BGD_SCE_TOOLS，请勿手改
-- 全局API聚合：api/ 目录下的每个模块自动挂载为 bgd_api.common.<模块名>
bgd_api.common = {}
bgd_api.common.class = require('libs.common.api.class')
bgd_api.common.co = require('libs.common.api.co')
bgd_api.common.deque = require('libs.common.api.deque')
bgd_api.common.event_deque = require('libs.common.api.event_deque')
bgd_api.common.exception = require('libs.common.api.exception')
bgd_api.common.json = require('libs.common.api.json')
bgd_api.common.promise = require('libs.common.api.promise')
bgd_api.common.read_db = require('libs.common.api.read_db')
