local keyboard = {
    ['a'] = 'A',
    ['b'] = 'B',
    ['c'] = "C",
    ['d'] = "D",
    ['e'] = "E",
    ['f'] = "F",
    ['g'] = "G",
    ['h'] = "H",
    ['i'] = "I",
    ['j'] = "J",
    ['k'] = "K",
    ['l'] = "L",
    ['m'] = "M",
    ['n'] = "N",
    ['o'] = "O",
    ['p'] = "P",
    ['q'] = "Q",
    ['r'] = "R",
    ['s'] = "S",
    ['t'] = "T",
    ['u'] = "U",
    ['v'] = "V",
    ['w'] = "W",
    ['x'] = "X",
    ['y'] = "Y",
    ['z'] = "Z",
    ['f1'] = "F1",
    ['f2'] = "F2",
    ['f3'] = "F3",
    ['f4'] = "F4",
    ['f5'] = "F5",
    ['f6'] = "F6",
    ['f7'] = "F7",
    ['f8'] = "F8",
    ['f9'] = "F9",
    ['f10'] = "F10",
    ['f11'] = "F11",
    ['f12'] = "F12",
    ['semicolon'] = ";",              --分号键
    ['minus'] = "Minus",              --减号键
    ['equals'] = "=",                 --等号键
    ['period'] = ".",                 --句号键
    ['slash'] = "/",                  --正斜杠键
    ['comma'] = ",",                  --逗号键
    ['backtick'] = "`",               --反引号键
    ['left_bracket'] = "[",           --左方括号键
    ['right_bracket'] = "]",          --右方括号键
    ['backslash'] = "\\",             --反斜杠键
    ['apostrophe'] = "\'",            --单引号键
    ['backspace'] = "BackSpace",      --撤销键
    ['tab'] = "Tab",                  --Tab键
    ['enter'] = "Enter",              --回车键
    ['pause'] = "Pause",              --暂停键
    ['caps_lock'] = "CapsLock",       --大写锁定键
    ['escape'] = "Escape",            --ESC键
    ['space'] = "SpaceBar",           --空格键
    ['page_up'] = "PageUp",           --上一页键
    ['page_down'] = "PageDown",       --下一页键
    ['end'] = "End",                  --End键
    ['home'] = "Home",                --Home键
    ['left'] = "Left",                --左键
    ['up'] = "Up",                    --上键
    ['right'] = "Right",              --右键
    ['down'] = "Down",                --下键
    ['print_screen'] = "PrintScreen", --截屏键
    ['insert'] = "Insert",            --插入键
    ['delete'] = "Delete",            --删除键
    ['scroll_lock'] = "ScrollLock",   --滚动锁定键
    ['shift'] = "Shift",              --Shift键
    ['left_shift'] = "LeftShift",     --左Shift
    ['right_shift'] = "RightShift",   --右Shift
    ['ctrl'] = "Ctrl",                --Ctrl键
    ['left_ctrl'] = "LeftCtrl",       --左Ctrl
    ['right_ctrl'] = "RightCtrl",     --右Ctrl
    ['alt'] = "Alt",                  --Alt键
    ['left_alt'] = "LeftAlt",         --左Alt
    ['right_alt'] = "RightAlt",       --右Alt
    ['num_0'] = "Num 0",              --数字0
    ['num_1'] = "Num 1",              --数字1
    ['num_2'] = "Num 2",              --数字2
    ['num_3'] = "Num 3",              --数字3
    ['num_4'] = "Num 4",              --数字4
    ['num_5'] = "Num 5",              --数字5
    ['num_6'] = "Num 6",              --数字6
    ['num_7'] = "Num 7",              --数字7
    ['num_8'] = "Num 8",              --数字8
    ['num_9'] = "Num 9",              --数字9
    ['num_plus'] = "Num +",           --数字+
    ['num_minus'] = "Num -",          --数字-
    ['num_asterisk'] = "Num *",       --数字*
    ['num_slash'] = "Num /",          --数字/
    ['num_period'] = "Num .",         --数字.
    ['num_lock'] = "NumLock",         --数字锁定键
    ['keypad_enter'] = "KeyPadEnter", --数字键盘回车键
}

bgd_const.keyboard = keyboard
